// <auto-generated />
using System;
using AP1_P1_StevenJavier.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP1_P1_StevenJavier.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("AP1_P1_StevenJavier.Models.Aportes", b =>
                {
                    b.Property<int>("AportesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Monto")
                        .HasColumnType("REAL");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .HasColumnType("TEXT");

                    b.HasKey("AportesId");

                    b.ToTable("Aportes");
                });
#pragma warning restore 612, 618
        }
    }
}
